// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZWxtcG4lGxKAy-_QPc10O4HNaqZ0NSJA',
    appId: '1:803363810749:web:82afb1d4378a669f70b6d4',
    messagingSenderId: '803363810749',
    projectId: 'kita-hack',
    authDomain: 'kita-hack.firebaseapp.com',
    storageBucket: 'kita-hack.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSPC5-Pav9MaKEwTrSIRqmU2eA1Gb3svM',
    appId: '1:803363810749:android:f77bc8ef539a9e0770b6d4',
    messagingSenderId: '803363810749',
    projectId: 'kita-hack',
    storageBucket: 'kita-hack.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2Z44Mqo68aaf9KTaq0tF3tu2e4cz9lAM',
    appId: '1:803363810749:ios:f069e0c1c8a5250e70b6d4',
    messagingSenderId: '803363810749',
    projectId: 'kita-hack',
    storageBucket: 'kita-hack.firebasestorage.app',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2Z44Mqo68aaf9KTaq0tF3tu2e4cz9lAM',
    appId: '1:803363810749:ios:f069e0c1c8a5250e70b6d4',
    messagingSenderId: '803363810749',
    projectId: 'kita-hack',
    storageBucket: 'kita-hack.firebasestorage.app',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZWxtcG4lGxKAy-_QPc10O4HNaqZ0NSJA',
    appId: '1:803363810749:web:70622f9f44cefb0f70b6d4',
    messagingSenderId: '803363810749',
    projectId: 'kita-hack',
    authDomain: 'kita-hack.firebaseapp.com',
    storageBucket: 'kita-hack.firebasestorage.app',
  );

}